# Generated by Django 3.2.3 on 2021-05-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refunds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='status',
            field=models.IntegerField(choices=[(0, 'resolved'), (1, 'unresolved')], default=1),
        ),
    ]
