# Generated by Django 3.2.3 on 2021-06-06 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
        ('refunds', '0002_refund_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='order_number',
        ),
        migrations.AddField(
            model_name='refund',
            name='order',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='checkout.order'),
            preserve_default=False,
        ),
    ]
