# Generated by Django 3.2.3 on 2021-06-06 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('refunds', '0006_auto_20210606_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='profiles.userprofile'),
        ),
    ]
