# Generated by Django 3.2.3 on 2021-06-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refunds', '0007_refund_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='order_number',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
