# Generated by Django 3.2.3 on 2021-05-29 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210529_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_profile',
        ),
    ]
